version: "3.4"

services: 
  groundskeeper:
    depends_on:
      - db
    image: ${DOCKER_REGISTRY-}groundskeeper
    build:
      context: .
      dockerfile: Groundskeeper/Dockerfile
  db: 
    environment: 
      MYSQL_DATABASE: groundkeeper
      MYSQL_PASSWORD: dbuserpassword
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: dbuser
    image: "mysql:5.7"
    restart: always
    ports:
     - 3306:3306
    volumes: 
      - "./_MySQL_Init_Script:/docker-entrypoint-initdb.d"
volumes: 
  db_data: